
version: '3.1'

services: 
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password 
    ports: 
       - "8080:8080"
    environment:
      MYSQL_DATABASE: MMS
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    volumes:
      - ./db:/var/lib/mysql            
    networks:
      - default
    restart: always
  backend:
    depends_on:
      - db
      - mq
    build: -> localizacao do dockerfile
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:8080-MMS?useSSL=true",
        "spring.datasource.username" : "user",
        "spring.datasource.password" : "user",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.rabbitmq.host" : "localhost",
        "spring.rabbitmq.port" : 5672,
        "spring.rabbitmq.username" : user,
        "spring.rabbitmq.password": user,
        "server.port": 8000
      }'
  mms-master:
    image: nginx # talvez não funcione, se não funcionar, criar Dockerfile e fazer build .
    ports: 
        - "8000:80"
    volumes:
        - ./mms-master:/var/www/html/
    links:
        - db
    networks:
        - default
    restart: always  
    
  mq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672 
